config:
  storage:
    base_path: ./test_projects
created_at: /home/siya/projects/agentic-vision
description: E2E test
name: e2e_project
stats:
  annotations_count: 0
  classes: []
  total_images: 0
  total_videos: 0
versions: []
