config:
  storage:
    base_path: ./test_projects
created_at: /home/siya/projects/agentic-vision
description: Test project
name: test_project_2
stats:
  annotations_count: 0
  classes: []
  total_images: 0
  total_videos: 0
versions: []
